import { PE_PRESENTATION_SELECTION } from "./presentation-policy.ts";
import { PE_TOOL_PROMPT_SNIPPETS } from "./tools/index.ts";

//hardcode暂时拼接
const PE_USER_name = "小天";

//【提示词】角色提示词
const PE_ROLE =
	"You are a PE (private equity research) expert operating inside PE-Workbench, a work agent harness which has coding ability. You help users by using financial tools to retrieve relevant information, as well as performing some general operations.";

// 保持 pi-agent 原内置四个工具的系统提示词
const PE_BASE_TOOLS = [
	{ name: "read", description: "Read file contents" },
	{ name: "bash", description: "Execute bash commands (ls, grep, find, etc.)" },
	{
		name: "edit",
		description: "Make precise file edits with exact text replacement, including multiple disjoint edits in one call",
	},
	{ name: "write", description: "Create or overwrite files" },
] as const;

//【提示词】工具列表,PE_BASE_TOOLS + PE_TOOL_PROMPT_SNIPPETS
export const toolsList = [...PE_BASE_TOOLS, ...PE_TOOL_PROMPT_SNIPPETS]
	.map(({ name, description }) => `- ${name}: ${description}`)
	.join("\n");

export function buildPeSystemPrompt(cwd: string): string {
	const promptCwd = cwd.replaceAll("\\", "/");
	//【提示词】用户相关
	const PE_USER = `You serve financial researcher ${PE_USER_name}.`;
	//【提示词】工作目录与目录架构规范（源码中有promptCwd）
	const PE_WORKSPACE = `The current project workspace is ${promptCwd}.
It has a fixed top-level structure:
- raw/: original research source materials.
- meta/: system-managed metadata, indexes, and project state.
- generated/: all user-visible outputs generated by the agent.
Do not rename, move, delete, or reorganize these directories, and do not create additional top-level directories.`;

	return `${PE_ROLE}

${PE_USER}

${PE_WORKSPACE}

Available tools:
${toolsList}

For PE evidence, place the exact markdown_citation after each material claim; never expose a bare evidence_id. Preserve the internal #pe-source?evidence_id= fragment exactly. It is an application action, not a website URL. Never expand it into https://pe-workbench.local, another host, a file link, or a source_collection URL. Green citation controls and their original-document preview must remain available in every presentation style.`;
}
