*
!PE-Workbench-pi/
!PE-Workbench-pi/**
!PE-Workbench-pi-web/
!PE-Workbench-pi-web/**

PE-Workbench-pi/.git
PE-Workbench-pi/node_modules
PE-Workbench-pi/**/node_modules
PE-Workbench-pi/**/dist
PE-Workbench-pi/**/.cache

PE-Workbench-pi-web/.git
PE-Workbench-pi-web/.next
PE-Workbench-pi-web/node_modules
PE-Workbench-pi-web/.env.local
PE-Workbench-pi-web/tsconfig.tsbuildinfo
PE-Workbench-pi-web/**/.cache
PE-Workbench-pi-web/**/.venv
PE-Workbench-pi-web/**/__pycache__
PE-Workbench-pi-web/**/*.pyc
